/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const YearNumber = IDL.Nat;
export const WeekNumber = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const TicketId = IDL.Nat;
export const DrawResult = IDL.Record({
  'pot' : IDL.Nat,
  'tickets' : IDL.Nat,
  'week' : WeekNumber,
  'year' : YearNumber,
  'winner' : IDL.Opt(IDL.Principal),
  'drawTime' : Time,
  'winningTicket' : IDL.Opt(TicketId),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToPot' : IDL.Func([IDL.Nat], [], []),
  'adminChangeRound' : IDL.Func([YearNumber, WeekNumber], [], []),
  'adminChangeTicketPrice' : IDL.Func([IDL.Nat], [], []),
  'adminSetup' : IDL.Func([YearNumber, WeekNumber], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buyTicket' : IDL.Func([], [], []),
  'getAdminWallet' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentRound' : IDL.Func(
      [],
      [YearNumber, WeekNumber, IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'getMyTickets' : IDL.Func([], [IDL.Nat], ['query']),
  'getPastDraws' : IDL.Func([IDL.Nat], [IDL.Vec(DrawResult)], ['query']),
  'getTicketPrice' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isLotteryAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminWallet' : IDL.Func([IDL.Principal], [], []),
  'setupLotteryAdmin' : IDL.Func([], [IDL.Bool], []),
  'triggerDraw' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const YearNumber = IDL.Nat;
  const WeekNumber = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const TicketId = IDL.Nat;
  const DrawResult = IDL.Record({
    'pot' : IDL.Nat,
    'tickets' : IDL.Nat,
    'week' : WeekNumber,
    'year' : YearNumber,
    'winner' : IDL.Opt(IDL.Principal),
    'drawTime' : Time,
    'winningTicket' : IDL.Opt(TicketId),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToPot' : IDL.Func([IDL.Nat], [], []),
    'adminChangeRound' : IDL.Func([YearNumber, WeekNumber], [], []),
    'adminChangeTicketPrice' : IDL.Func([IDL.Nat], [], []),
    'adminSetup' : IDL.Func([YearNumber, WeekNumber], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buyTicket' : IDL.Func([], [], []),
    'getAdminWallet' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentRound' : IDL.Func(
        [],
        [YearNumber, WeekNumber, IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getMyTickets' : IDL.Func([], [IDL.Nat], ['query']),
    'getPastDraws' : IDL.Func([IDL.Nat], [IDL.Vec(DrawResult)], ['query']),
    'getTicketPrice' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isLotteryAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminWallet' : IDL.Func([IDL.Principal], [], []),
    'setupLotteryAdmin' : IDL.Func([], [IDL.Bool], []),
    'triggerDraw' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
