/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DrawResult {
  'pot' : bigint,
  'tickets' : bigint,
  'week' : WeekNumber,
  'year' : YearNumber,
  'winner' : [] | [Principal],
  'drawTime' : Time,
  'winningTicket' : [] | [TicketId],
}
export type TicketId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WeekNumber = bigint;
export type YearNumber = bigint;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToPot' : ActorMethod<[bigint], undefined>,
  'adminChangeRound' : ActorMethod<[YearNumber, WeekNumber], undefined>,
  'adminChangeTicketPrice' : ActorMethod<[bigint], undefined>,
  'adminSetup' : ActorMethod<[YearNumber, WeekNumber], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buyTicket' : ActorMethod<[], undefined>,
  'getAdminWallet' : ActorMethod<[], [] | [Principal]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentRound' : ActorMethod<[], [YearNumber, WeekNumber, bigint, bigint]>,
  'getMyTickets' : ActorMethod<[], bigint>,
  'getPastDraws' : ActorMethod<[bigint], Array<DrawResult>>,
  'getTicketPrice' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isLotteryAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminWallet' : ActorMethod<[Principal], undefined>,
  'setupLotteryAdmin' : ActorMethod<[], boolean>,
  'triggerDraw' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
